# Broadcasting - different shaped array

In [2]:
import numpy as np

### Practice ques1

In [4]:
arr1 = np.arange(12).reshape(4,3)
arr2 = np.arange(3)

print(arr1)
print(arr2)

# it will be automatically brodcasted 
print(arr1 + arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


### Practice ques 2

In [5]:
arr1 = np.arange(3).reshape(1,3)
arr2 = np.arange(3).reshape(3,1)

print(arr1)
print(arr2)

# it will be automatically brodcasted 
print(arr1 + arr2)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
