# Broadcasting - same shaped array

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

print(arr1)
print(arr2)

print(arr1 + arr2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]
