# Boolean indexing 

In [2]:
import numpy as np

In [3]:
# creating an array

arr = np.random.randint(1,100,24).reshape(6,4)
print(arr)

[[45 87 67 26]
 [65 11 51 24]
 [13  9 28 88]
 [32 50 63 65]
 [99 99 31 31]
 [89 80 46 19]]


## when we have to get data by implimenting logic eg. get all even numbers between 1-100

In [ ]:
# boolean indexing
# ques 1 - find all numbers greater than 50

print(arr > 50) 

[[False  True  True False]
 [ True False  True False]
 [False False False  True]
 [False False  True  True]
 [ True  True False False]
 [ True  True False False]]


In [12]:
# find all numbers greater than 50 and even
print((arr > 50 ) & (arr % 2 ==0))

[[False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]
 [False False False False]
 [False  True False False]]


In [13]:
# find all numbers that are not divisible by 7
print(arr % 7 != 0)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
