# Fancy indexing 

In [3]:
import numpy as np

In [6]:
# creating an array

arr = np.arange(12).reshape(4,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## suppose we want only 0,2,3 column only then with normal slicing we can't do this.
## so we use fancy indexing in square brackets [] we pass list inside [[]] with column index eg. [[0,2,3]]

In [7]:
# fancy indexing
arr[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])